### ISSUE TITLE
Add doco for making commits signed

### ISSUE THREAD

**Issue by bhamail** [sonatype-nexus-community/community-project-template#15]
Provide/link to doco to make sure your commits are signed.

Case in point: bad toad: https://github.com/sonatype-nexus-community/the-cla/pull/70/commits/4f21b90348369979f28519008ad2a923d6ac0a3d

**Comment by bhamail** [comment]
This looks promising: 
1. https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification

2. https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-gpg-key

**Comment by madpah** [comment]
Resolved by #16
