### ISSUE TITLE
Remove CODE_OF_CONDUCT.md in favour of global Organization one

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/community-project-template#17]
As per https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file, we can create this once in then `.github` repository (already done).

FYI @eddie-knight @hboutemy @bhamail

**Comment by hboutemy** [comment]
https://github.com/sonatype-nexus-community/.github/blob/main/CODE_OF_CONDUCT.md
